#include <stdio.h>
#include "parser.tab.h" // Generated by Bison
#include "ast.h"

extern FILE *yyin;
extern int yyparse();
extern int symbolCount;

ASTNode* parse_program(const char* filename) {
    FILE *file = fopen(filename, "r");
    if (!file) {
        perror("apsh: submit");
        return NULL;
    }

    symbolCount = 0;

    yyin = file;
    int result = yyparse();
    fclose(file);

    if (result == 0) {
        return root; // Return the AST root built during yyparse
    }
    return NULL;
}